# This file is used to compile the LemShell project.
# If additional files are added to the project, they should be added to the list of files to compile.
all:
	g++ lemshell.cpp -o lemshell bi_com.cpp styler.cpp 